/*
 * This source file was generated by the Gradle 'init' task
 */
package com.aoc;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class Day02Test {

    @Test void shouldReturnDemoValue2() throws Exception {
        Day02 classUnderTest = new Day02();
        var demoFile = "./day02/demo.input";
        assertEquals(classUnderTest.runPart1(demoFile), 2);
    }

    @Test void shouldReturnResultOfPartOne() throws Exception {
        Day02 classUnderTest = new Day02();
        var demoFile = "./day02/puzzle.input";
        assertEquals(classUnderTest.runPart1(demoFile), 359);
    }

    @Test void shouldReturnDemoValue4() throws Exception {
        Day02 classUnderTest = new Day02();
        var demoFile = "./day02/demo.input";
        assertEquals(classUnderTest.runPart2(demoFile), 4);
    }
}
